version: 2.1
orbs:
  docker: circleci/docker@2.2.0
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - docker/install-docker-compose
      - run: docker-compose up -d
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: cd ./app && poetry run pytest
      - persist_to_workspace:
          root: .
          paths:
            - .
    

workflows:
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build