version: 2.1
orbs:
  docker: circleci/docker@2.2.0
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-ecs: circleci/aws-ecs@3.2.0
jobs:
  test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - docker/install-docker-compose
      - run: docker-compose up -d
      - run: pip install poetry
      - run: cd app/ && poetry  install && poetry run playwright install --with-deps
      - run: cd app/ && bash test.sh
      - run: cd app/ && poetry run pytest

workflows:
  integration_tests:
    jobs:
      - test
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          dockerfile: <my-Docker-file>
          path: <path-to-my-Docker-file>
          profile-name: <my-profile-name>
          repo: ${MY_APP_PREFIX}
          tag: '${CIRCLE_SHA1}'
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image # only run the deployment job once the build and push image job has completed
          family: '${MY_APP_PREFIX}-service'
          cluster: '${MY_APP_PREFIX}-cluster'
          container-image-name-updates: 'container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}'